### ISSUE TITLE
Docker and curl commands in functions/README.md don't work.

### ISSUE THREAD

**Issue by jconning** [iron-io/functions#512] opened 2017-02-04 17:52 UTC
~~`curl get.iron.io/fn` needs a -L so it can follow the redirect.~~
`${pwd}` in docker run should actually be `${PWD}`.

Fix the README.md so that these commands work out of the box.

**Comment by treeder** [comment] 2017-02-04 20:32
The fn part of this is a dupe of #501 .

**Comment by jconning** [comment] 2017-02-07 22:05
These are both valid curl commands that do different things:
`curl -sSL`
`curl --ssl`

Maybe I'm the only nutcase who would ever be confused by this but what the heck I changed it to be `curl -LSs`.

**Closed** 2017-02-08 21:16 UTC
